# This workflow deploys the YMOL lambda code to the QA/development environment.

name: CDK Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pip & poetry
      run: |
        python -m pip install --upgrade pip poetry

    # create a requirements file that can be used later by the cdk deploy step
    - name: Export dependencies
      run: |
        poetry export -f requirements.txt --output requirements.txt

    # this is the build step for the lambda code
    - name: Build Lambda
      run: |
        cd src/lambda_code/api_gw_lambda
        pip install -r requirements.txt -t .

    # the deployment step expects AWS CDK python dependencies in a requirements.txt in its working directory.
    # poetry export above should have placed it at src/requirements.txt
    - name: CDK Deploy
      uses: youyo/aws-cdk-github-actions@v1
      with:
        cdk_subcommand: 'deploy'
        cdk_stack: 'mvp-data-pipeline-aws'
        actions_comment: false
        working_dir: '.'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWSPUBLICKEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETKEY }}
        AWS_DEFAULT_REGION: 'eu-west-1'
